# Generated by Django 5.2.1 on 2025-05-17 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.prod_proveedor')),
            ],
        ),
    ]
