# Generated by Django 5.2.1 on 2025-05-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_orden_productoorden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'managed': False, 'verbose_name': 'regprovs_marca'},
        ),
        migrations.AlterModelOptions(
            name='prod_proveedor',
            options={'managed': False, 'verbose_name': 'regprovs_prod_proveedor'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False, 'verbose_name': 'regprovs_proveedor'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'managed': False, 'verbose_name': 'regprovs_tipo'},
        ),
    ]
