# Generated by Django 5.2.1 on 2025-05-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_marca_options_alter_prod_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prod_proveedor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='marca',
            table='proveedores_marca',
        ),
        migrations.AlterModelTable(
            name='prod_proveedor',
            table='proveedores_prod_proveedor',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedores_proveedor',
        ),
        migrations.AlterModelTable(
            name='tipo',
            table='proveedores_tipo',
        ),
    ]
