# Generated by Django 5.2.1 on 2025-05-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_marca_options_alter_prod_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marca',
            table='regprovs_marca',
        ),
        migrations.AlterModelTable(
            name='prod_proveedor',
            table='regprovs_prod_proveedor',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='regprovs_proveedor',
        ),
        migrations.AlterModelTable(
            name='tipo',
            table='regprovs_tipo',
        ),
    ]
