# Generated by Django 5.2.1 on 2025-05-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_marca_table_alter_prod_proveedor_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productoorden',
            options={'managed': False},
        ),
    ]
